import type { PlaceAltitudeAdvisorData, PlaceFeeData, PlaceSafetyData } from "./types";

export const FALLBACK_SAFETY: Record<string, Omit<PlaceSafetyData, 'contextType'>> = {
  "mount-bromo": {
    name: "Mount Bromo Crater Viewpoint",
    status: "open",
    details: "Weather clear. Normal activity. All main viewpoints (Penanjakan, King Kong Hill) accessible.",
    last_updated: "2026-07-15T12:00:00Z"
  },
  "tumpak-sewu": {
    name: "Tumpak Sewu Waterfall Ravine Trail",
    status: "caution",
    details: "Water levels elevated due to afternoon rainfall. Use caution on the lower descent paths.",
    last_updated: "2026-07-15T12:00:00Z"
  },
  "pantai-3-warna": {
    name: "Pantai 3 Warna Conservation Path",
    status: "open",
    details: "All beach pathways open. Swimming allowed in designated colored zones.",
    last_updated: "2026-07-15T12:00:00Z"
  },
  "coban-pelangi": {
    name: "Coban Pelangi Waterfall Trail",
    status: "open",
    details: "Trail open and dry. Safe for walking down to the river bed.",
    last_updated: "2026-07-15T12:00:00Z"
  },
  "pulau-sempu": {
    name: "Pulau Sempu Nature Trail",
    status: "caution",
    details: "Hutan trail path is muddy and slick. Only allowed with registered local guides.",
    last_updated: "2026-07-15T12:00:00Z"
  },
  "budug-asu": {
    name: "Budug Asu Ridge Road",
    status: "open",
    details: "Dry, clear conditions on the dirt track. Accessible to offroad vehicles.",
    last_updated: "2026-07-15T12:00:00Z"
  },
  "jatim-park-1": {
    name: "Jatim Park 1 Walkways",
    status: "open",
    details: "Amusement park trails completely open and safe.",
    last_updated: "2026-07-15T12:00:00Z"
  },
  "museum-angkut": {
    name: "Museum Angkut Exhibit Halls",
    status: "open",
    details: "Indoor and outdoor vintage galleries open to visitors.",
    last_updated: "2026-07-15T12:00:00Z"
  },
  "kayutangan-heritage": {
    name: "Kayutangan Heritage Zone",
    status: "open",
    details: "Colonial residential streets and historic buildings open to the public.",
    last_updated: "2026-07-15T12:00:00Z"
  },
  "sumber-sirah": {
    name: "Sumber Sirah Springs",
    status: "open",
    details: "Spring pool and surrounding paddy paths open and clear.",
    last_updated: "2026-07-15T12:00:00Z"
  },
  "nakoa-coffee": {
    name: "Nakoa Coffee space",
    status: "open",
    details: "Workspace completely open.",
    last_updated: "2026-07-15T12:00:00Z"
  }
};

export const FALLBACK_FEES: Record<string, PlaceFeeData> = {
  "mount-bromo": {
    domestic_entry: 29000,
    foreign_entry: 220000,
    transport_cost: 650000,
    parking_cost: 10000,
    notes: "Jeep hire is mandatory and cash-only to traverse the sea of sand. Weekend domestic rate is Rp 34,500.",
    atm_info: "Last reliable ATMs are in Sukapura (18km) or Tumpang (22km). No ATMs near the crater.",
  },
  "tumpak-sewu": {
    domestic_entry: 10000,
    foreign_entry: 20000,
    transport_cost: 0,
    parking_cost: 5000,
    notes: "Optional trail safety guides at the bottom cost ~IDR 100,000 cash.",
    atm_info: "Nearest ATM is at Pronojiwo local market (3km away).",
  },
  "pantai-3-warna": {
    domestic_entry: 15000,
    foreign_entry: 100000,
    transport_cost: 150000,
    parking_cost: 10000,
    notes: "Pre-booking mandatory. Guide fee (Rp 150,000/group) is required for conservation zone access.",
    atm_info: "Nearest ATM is in Sendang Biru village (2.5km) — frequently runs out of cash.",
  },
  "coban-pelangi": {
    domestic_entry: 10000,
    foreign_entry: 50000,
    transport_cost: 0,
    parking_cost: 5000,
    notes: "Weekend rate is Rp 15,000. Food and drinks stalls near the entrance are cash-only.",
    atm_info: "Last reliable ATM is at Poncokusumo village center (8km away).",
  },
  "pulau-sempu": {
    domestic_entry: 20000,
    foreign_entry: 150000,
    transport_cost: 150000,
    parking_cost: 10000,
    notes: "BKSDA permit required at the Sendang Biru conservation office. Boat transport is cash-only.",
    atm_info: "ATM availability at Sendang Biru is extremely limited. Withdraw cash in Malang or Turen.",
  },
  "budug-asu": {
    domestic_entry: 10000,
    foreign_entry: 50000,
    transport_cost: 200000,
    parking_cost: 5000,
    notes: "Motorcycle trail access fee is Rp 20,000. Site is entirely cash-only.",
    atm_info: "Nearest ATMs are at Lawang town center (12km away).",
  },
  "wonosari-tea-plantation": {
    domestic_entry: 15000,
    foreign_entry: 50000,
    transport_cost: 0,
    parking_cost: 5000,
    notes: "Weekend rate is Rp 20,000. Factory tour and tea tasting may have a small additional fee.",
    atm_info: "Nearest ATM is in Lawang town center (7km away).",
  },
  "coban-rondo-waterfall": {
    domestic_entry: 35000,
    foreign_entry: 100000,
    transport_cost: 0,
    parking_cost: 5000,
    notes: "Ticket includes access to the labyrinth maze, pine forest walk, and several small attractions.",
    atm_info: "No ATMs at the waterfall. Nearest ATM is in Pujon town (4km).",
  },
  "paralayang-batu-omah-kayu": {
    domestic_entry: 10000,
    foreign_entry: 30000,
    transport_cost: 0,
    parking_cost: 5000,
    notes: "Tandem paragliding costs Rp 400,000–500,000 and is booked separately with local operators.",
    atm_info: "Nearest ATMs are in Batu city center (3km away).",
  },
  "selecta-park": {
    domestic_entry: 50000,
    foreign_entry: 100000,
    transport_cost: 0,
    parking_cost: 5000,
    notes: "Ticket includes access to the flower garden, swimming pool, and children's play area.",
    atm_info: "ATMs available in Selecta village nearby and in Batu city center (8km).",
  },
  "coban-rais": {
    domestic_entry: 10000,
    foreign_entry: 50000,
    transport_cost: 0,
    parking_cost: 5000,
    notes: "Access to Batu Flower Garden requires a separate Rp 25,000 ticket. Entrance via Coban Rais gate.",
    atm_info: "Nearest ATMs are in Batu city center (5km away).",
  },
  "jatim-park-1": {
    domestic_entry: 115000,
    foreign_entry: 150000,
    transport_cost: 0,
    parking_cost: 10000,
    notes: "Combo tickets with Museum Angkut or Museum Tubuh give better value. QRIS & cards accepted.",
    atm_info: "Several ATM kiosks are available directly at the main entrance gate.",
  },
  "museum-angkut": {
    domestic_entry: 110000,
    foreign_entry: 150000,
    transport_cost: 0,
    parking_cost: 10000,
    notes: "Combo tickets with Jatim Park 1 give better value. QRIS and card accepted at all counters.",
    atm_info: "ATMs are located inside the floating market area and near the ticket booths.",
  },
  "jatim-park-2-secret-zoo": {
    domestic_entry: 125000,
    foreign_entry: 200000,
    transport_cost: 0,
    parking_cost: 10000,
    notes: "Ticket includes access to both Batu Secret Zoo and Museum Satwa. QRIS accepted.",
    atm_info: "ATMs are available at the entrance gate area.",
  },
  "jatim-park-3-dino-park": {
    domestic_entry: 100000,
    foreign_entry: 175000,
    transport_cost: 0,
    parking_cost: 10000,
    notes: "Price varies by zone (Rp 100,000–190,000). Combo packages with Legend Stars available.",
    atm_info: "ATMs located at the main entrance and inside the park near food courts.",
  },
  "batu-night-spectacular": {
    domestic_entry: 35000,
    foreign_entry: 75000,
    transport_cost: 0,
    parking_cost: 5000,
    notes: "Weekend entrance is Rp 40,000. All-ride pass (31 rides) costs Rp 110,000–120,000 separately.",
    atm_info: "ATM kiosks available at the main entrance. QRIS accepted at ticket counters.",
  },
  "kampung-warna-warni-jodipan": {
    domestic_entry: 5000,
    foreign_entry: 10000,
    transport_cost: 0,
    parking_cost: 2000,
    notes: "Small entrance fee supports the local kampung community maintenance fund.",
    atm_info: "Located in central Malang. Multiple ATMs within a 10-minute walk.",
  },
  "malang-night-paradise": {
    domestic_entry: 75000,
    foreign_entry: 120000,
    transport_cost: 0,
    parking_cost: 5000,
    notes: "Weekend rate is Rp 80,000. All-ride pass available from Rp 160,000. QRIS accepted.",
    atm_info: "ATMs available near the main entrance and in nearby Dinoyo area.",
  },
  "hawai-waterpark": {
    domestic_entry: 85000,
    foreign_entry: 150000,
    transport_cost: 0,
    parking_cost: 10000,
    notes: "Weekend/high season rate is Rp 120,000. Children under 85cm enter free.",
    atm_info: "ATM available at the park entrance. BRI and BCA ATMs in the nearby mall.",
  },
  "san-terra-del-fonte": {
    domestic_entry: 25000,
    foreign_entry: 50000,
    transport_cost: 0,
    parking_cost: 5000,
    notes: "Weekend rate is Rp 30,000–35,000. Individual ride attractions cost extra (Rp 5,000–30,000 each).",
    atm_info: "Nearest ATMs are in Batu city center (4km away).",
  },
  "predator-fun-park": {
    domestic_entry: 0,
    foreign_entry: 0,
    transport_cost: 0,
    parking_cost: 5000,
    notes: "Entry is free. Rides and crocodile show attractions are pay-per-ride (approx Rp 10,000–30,000 each).",
    atm_info: "Nearest ATMs are in Batu city center (3km away).",
  },
  "kayutangan-heritage": {
    domestic_entry: 5000,
    foreign_entry: 10000,
    transport_cost: 0,
    parking_cost: 3000,
    notes: "Main street is free to walk. Rp 5,000 fee applies only to the heritage alley kampung area.",
    atm_info: "Located in Malang city center. Dozens of ATMs within a 5-minute walk.",
  },
  "alun-alun-malang": {
    domestic_entry: 0,
    foreign_entry: 0,
    transport_cost: 0,
    parking_cost: 3000,
    notes: "Completely free public square. Street food and drinks stalls are cash-only.",
    atm_info: "Central Malang location — ATMs from all major banks within walking distance.",
  },
  "candi-singosari": {
    domestic_entry: 0,
    foreign_entry: 0,
    transport_cost: 0,
    parking_cost: 2000,
    notes: "Free entry. A voluntary donation box is available at the temple grounds for preservation.",
    atm_info: "Nearest ATMs are in Singosari town center (1.5km away).",
  },
  "tugu-malang": {
    domestic_entry: 0,
    foreign_entry: 0,
    transport_cost: 0,
    parking_cost: 3000,
    notes: "Outdoor public monument — completely free to visit at any time of day.",
    atm_info: "Central Malang location — ATMs from all major banks within walking distance.",
  },
  "candi-badut": {
    domestic_entry: 0,
    foreign_entry: 0,
    transport_cost: 0,
    parking_cost: 2000,
    notes: "Free entry. Managed by local community. Donations welcome for site upkeep.",
    atm_info: "Nearest ATMs are in Dinoyo area (2km away).",
  },
  "gereja-ijen": {
    domestic_entry: 0,
    foreign_entry: 0,
    transport_cost: 0,
    parking_cost: 3000,
    notes: "Free entry. Respectful dress code required. Avoid visiting during Sunday mass hours.",
    atm_info: "Located in central Malang. ATMs from all major banks within walking distance.",
  },
  "klenteng-eng-an-kiong": {
    domestic_entry: 0,
    foreign_entry: 0,
    transport_cost: 0,
    parking_cost: 2000,
    notes: "Free entry. Donations welcome. Respectful attire required. Extra busy during Chinese New Year.",
    atm_info: "Located in Malang Chinatown area. ATMs available within a 5-minute walk.",
  },
  "monumen-juang-45": {
    domestic_entry: 0,
    foreign_entry: 0,
    transport_cost: 0,
    parking_cost: 2000,
    notes: "Outdoor public monument — entirely free to visit. Bring water as there are no facilities.",
    atm_info: "Located near the Malang city center. ATMs available within a 10-minute walk.",
  },
  "candi-kidal": {
    domestic_entry: 0,
    foreign_entry: 0,
    transport_cost: 0,
    parking_cost: 2000,
    notes: "Free entry. Voluntary donations help maintain this 13th-century heritage site.",
    atm_info: "Nearest ATMs are in Tumpang town center (4km away).",
  },
  "candi-jago": {
    domestic_entry: 10000,
    foreign_entry: 50000,
    transport_cost: 0,
    parking_cost: 2000,
    notes: "Weekend rate is Rp 15,000. Managed by BPCB (Heritage Conservation Board).",
    atm_info: "Nearest ATMs are in Tumpang town center (2km away).",
  },
  "museum-musik-indonesia": {
    domestic_entry: 10000,
    foreign_entry: 30000,
    transport_cost: 0,
    parking_cost: 3000,
    notes: "Ticket includes one complimentary vinyl record play session in the listening room.",
    atm_info: "Nearest ATMs are in Batu city center (2km away).",
  },
  "museum-brawijaya": {
    domestic_entry: 5000,
    foreign_entry: 20000,
    transport_cost: 0,
    parking_cost: 3000,
    notes: "Children's rate is Rp 3,000. Open Mon–Thu 08:00–14:30 WIB, Fri until 11:30 WIB.",
    atm_info: "Located in central Malang. ATMs from all major banks within walking distance.",
  },
  "sumber-sirah": {
    domestic_entry: 5000,
    foreign_entry: 15000,
    transport_cost: 0,
    parking_cost: 3000,
    notes: "River tube rental is Rp 10,000 in cash. Bring plastic bags to protect your belongings.",
    atm_info: "Nearest ATM is at the Gondanglegi main road (4.5km away).",
  },
  "sumber-maron": {
    domestic_entry: 5000,
    foreign_entry: 15000,
    transport_cost: 0,
    parking_cost: 3000,
    notes: "Weekend rate is Rp 10,000. Inner tube rental available for Rp 10,000 cash.",
    atm_info: "Nearest ATMs are in Kepanjen town center (7km away).",
  },
  "sumber-jenon": {
    domestic_entry: 10000,
    foreign_entry: 25000,
    transport_cost: 0,
    parking_cost: 3000,
    notes: "Natural spring pool. Entirely cash-only. No food vendors inside — bring your own snacks.",
    atm_info: "Nearest ATMs are in Tajinan town (5km away).",
  },
  "coban-sumber-pitu-pujon": {
    domestic_entry: 10000,
    foreign_entry: 30000,
    transport_cost: 0,
    parking_cost: 5000,
    notes: "Local guide recommended for the full 7-waterfall route (approx Rp 100,000 per group).",
    atm_info: "Nearest ATMs are in Pujon town center (6km away).",
  },
  "pantai-gatra": {
    domestic_entry: 10000,
    foreign_entry: 30000,
    transport_cost: 0,
    parking_cost: 5000,
    notes: "Conservation beach — no littering strictly enforced. Bring all your own food and water.",
    atm_info: "No ATMs near the beach. Withdraw cash in Malang city before departure.",
  },
  "candi-sumberawan": {
    domestic_entry: 5000,
    foreign_entry: 15000,
    transport_cost: 0,
    parking_cost: 2000,
    notes: "Set beside a sacred spring. Quiet, off-the-beaten-path site with minimal facilities.",
    atm_info: "Nearest ATMs are in Singosari town center (3km away).",
  },
  "lembah-indah-malang": {
    domestic_entry: 20000,
    foreign_entry: 50000,
    transport_cost: 0,
    parking_cost: 5000,
    notes: "Area access only. Accommodation, camping, and extra activities are billed separately.",
    atm_info: "No ATMs on-site. Withdraw cash in Malang city (15km) before arrival.",
  },
  "nakoa-coffee": {
    domestic_entry: 0,
    foreign_entry: 0,
    transport_cost: 0,
    parking_cost: 2000,
    notes: "Cafe space. Payment fully via Credit/Debit cards or QRIS.",
    atm_info: "ATM kiosk at the convenience store right across the street.",
  }
};

export const FALLBACK_ALTITUDES: Record<string, PlaceAltitudeAdvisorData> = {
  "mount-bromo": { altitude: 2329, temp_range: "3°C - 15°C", packing_list: "Thick Winter Jacket, Gloves, Beanie, Scarf, Closed Hiking Shoes" },
  "tumpak-sewu": { altitude: 500, temp_range: "20°C - 28°C", packing_list: "Waterproof Shoes/Sandals, Change of Clothes, Dry Bag, Raincoat" },
  "pantai-3-warna": { altitude: 5, temp_range: "25°C - 32°C", packing_list: "Swimwear, Sunscreen, Change of Clothes, Waterproof Bag, Sandals" },
  "coban-pelangi": { altitude: 1300, temp_range: "14°C - 21°C", packing_list: "Light Jacket, Non-slip Sneakers, Umbrella/Raincoat" },
  "pulau-sempu": { altitude: 5, temp_range: "24°C - 31°C", packing_list: "Sturdy Hiking Shoes, Mosquito Repellent, Tent (if camping), Headlamp" },
  "budug-asu": { altitude: 1400, temp_range: "13°C - 20°C", packing_list: "Windbreaker, Hiking boots, Warm Layer" },
  "jatim-park-1": { altitude: 900, temp_range: "18°C - 25°C", packing_list: "Comfortable Sneakers, Cap, Light Casual clothing" },
  "museum-angkut": { altitude: 900, temp_range: "18°C - 25°C", packing_list: "Casual Walking Shoes, Camera, Light Clothes" },
  "kayutangan-heritage": { altitude: 440, temp_range: "22°C - 30°C", packing_list: "Comfortable Sandals/Shoes, Camera, Light Summer clothing" },
  "sumber-sirah": { altitude: 350, temp_range: "23°C - 30°C", packing_list: "Towels, Change of Clothes, Swimming gear, Goggles" },
  "nakoa-coffee": { altitude: 440, temp_range: "22°C - 28°C", packing_list: "Laptop, Casual Wear, Charger" }
};

export const FALLBACK_ALTITUDE_ENTRIES = Object.entries(FALLBACK_ALTITUDES).map(([slug, data]) => ({
  slug,
  ...data,
}));
